spring:
  # PostgreSQL Configuration (for transactional data)
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_db
    username: booking_user
    password: booking123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  # MongoDB Configuration (for catalog data)
  data:
    mongodb:
      uri: mongodb://localhost:27017/booking_catalog
    
    # Redis Configuration (for caching)
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  


  # Security configuration
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

# Cache configuration
cache:
  redis:
    ttl: 300 # 5 minutes